### ISSUE TITLE
Interpolation Problem (LibSass related?) - Found Fix

### ISSUE THREAD

**Issue by isaaki** [typeplate/starter-kit#23]
Greetings,

First off, love the project. Many thanks for your work. 

Now, I'm using LibSass (via GulpSass) to compile. In general, LibSass is always a bit slow to implement new Sass features (though it's incredibly fast, which is why I use it). Anyways, I found that some of the typeplate functions were being returned with spaces between measurements and their values (like `font-size: 32 rem` instead of `font:size: 32rem'), so naturally this was read by the browser and the User Agent Stylesheet defaults were being used. 

Took me a while to realize what was going on, but here's the fix that worked for me:

**Around line `200` of _typeplate.scss**
```
@function context-calc($scale, $base, $value) {
  @return ($scale/$base) + $value;    // was @return ($scale/$base)#{$value};
}
@function measure-margin($scale, $measure, $value) {
  @return ($measure/$scale) + $value;    /// was @return ($measure/$scale)#{$value};
}
```
**And in the line `225` block:**
```
@if $value == 
  font-size: #{$scale + px};    // was font-size: $scale#{px};
}
```

Not sure if this should be integrated into a pull request or if you'd rather leave things as they were before for some reason. Not sure if this will cause issues for other Sass compiling methods, but it's working for me.

**Comment by blustemy** [comment]
Hi,

I'm still getting the error with the extra space before the unit with libSass. But this is the fix I'm using in `_typeplate-functions.scss`:

```scss
@function typl8-context-calc($scale, $base, $value) {
  @return #{$scale/$base}#{$value}; // chaining two interpolations
}
```

And:

```scss
@function typl8-measure-margin($scale, $measure, $value) {
  $pixelValue: $measure/$scale;
  $remValue: $pixelValue * $typl8-font-base;

  @if $value == rem {
    @return #{$pixelValue}#{$value};
  } @else if $value == em {
    @return #{$remValue/$scale}#{$value};
  } @else {
    @return #{$remValue}#{$value};
  }
}
```

And I love Typeplate too!

Thanks,

Fred

**Comment by grayghostvisuals** [comment]
@blustemy If you click [here](https://github.com/sass/libsass/issues/442) you'll see this is still not resolved on libsass' end. Sorry, but it's in their field right now. Thanks btw for the kind words. I'm glad you find this project useful. I use it everyday myself :)

**Comment by ramsaylanier** [comment]
@blustemy  +1 - this fixed worked for me.

**Comment by grayghostvisuals** [comment]
Here's the fix I plan to implement in Sassmeister until I can merge the code into the project [http://sassmeister.com/gist/f8197ffbac32689e84a8](http://sassmeister.com/gist/f8197ffbac32689e84a8)

**Comment by HugoGiraudel** [comment]
Just to clarify what is going on: there is indeed an issue on LibSass end with string interpolation. Actually, it is not the first one, and will probably not be the last. That being said, the issue should not be a problem for Typeplate whatsoever when doing things slightly more elegantly. 

Basically the problem here is that we deal with units as if they were random strings living on the right of some numbers. This is not how it works. We gotta see units as if they were completely indivisible from numbers. Units cannot live on their own.

My point is, rather than appending the unit as a string at the end of a number, we better multiply that number by 1 of this unit (or add 0 of this unit, it works as well).

So instead of:

```scss
@function typl8-measure-margin($scale, $measure, $value) {
  $pixelValue: $measure/$scale;
  $remValue: $pixelValue * $typl8-font-base;

  @if $value == rem {
    @return $pixelValue#{$value};
  } @else if $value == em {
    @return ($remValue/$scale)#{$value};
  } @else {
    @return $remValue#{$value};
  }
}
```

We could have:

```scss
@function typl8-measure-margin($scale, $measure, $value) {
  $pixel-value: ($measure / $scale);
  $rem-value: ($pixelValue * $typl8-font-base);

  @if unit($value) == 'rem' {
    @return $pixel-value * $value;
  } @else if unit($value) == 'em' {
    @return ($rem-value / $scale) * $value;
  } @else {
    @return $rem-value * $value;
  }
}
```

Or a bit more elegant (at least to me):

```scss
@function typl8-measure-margin($scale, $measure, $value) {
  $pixel-value: ($measure / $scale);
  $rem-value: ($pixelValue * $typl8-font-base);
  
  @if unit($value) == 'rem' {
    $v: $pixel-value;
  } @else if unit($value) == 'em' {
    $v: ($rem-value / $scale);
  } @else {
    $v: $rem-value;
  }
  
  @return $v * $value;
}
```

So at the end of the day, all we need is to make `$value` 1 item of a unit, for instance `1px` rather than a string like `px`.
